### ISSUE TITLE
Add Torii configuration file and ERC indexing

### ISSUE THREAD

**Issue by glihm** [cartridge-gg/slot#116]
Torii can now index ERCs and relies on a configuration file to do so.
As the genesis file for Katana, the configuration file for Torii must be sent to via slot CLI to actually unlock the option on the infrastructure side.

**Comment by rsodre** [comment]
What about something like overlays for configuring torii tokens? We might need the addresses of contracts deployed with the Dojo World.

Also, contents may vary on different profiles.

example:

```toml
# dev profile
contracts = [
  { type = "ERC721", address = "$contract_address:pistols-duelists" },
  { type = "ERC20", address = "$contract_address:pistols-mock-lords" },
]
```

```toml
# production profile
contracts = [
  { type = "ERC721", address = "$contract_address:pistols-duelists" },
  { type = "ERC20", address = "0x044e6bcc627e6201ce09f781d1aae44ea4c21c2fdef299e34fce55bef2d02210" },
]
```

**Comment by glihm** [comment]
Was added in recent versions using the `--indexing.contracts` or the config file directly. 👍
