### ISSUE TITLE
Dump predeployed accounts

### ISSUE THREAD

**Issue by broody** [cartridge-gg/slot#18]
Make it easier to retrieve predeployed accounts, maybe something like this

`slot deployments accounts {project} {service}`

**Comment by tarrencev** [comment]
100%

i think we might want to duplicate the contract calculation logic from katana to do this

**Comment by broody** [comment]
Briefly went down the path of trying to add katana-core as a dependency to use its `DevAccountGenerator` but some weird build issues. 

Also, wonder if it make sense for katana to expose a `predeployedAccounts` in non-dev mode but requires a seed input.
