### ISSUE TITLE
Cleanup hardcoded URL values with env

### ISSUE THREAD

**Issue by steebchen** [cartridge-gg/slot#67]
https://github.com/cartridge-gg/slot/blob/d87a0bc918711b7c4da7c56b71535dc38cbf1bdb/cli/src/command/auth/login.rs#L37

some hardcoded things https://github.com/cartridge-gg/slot/blob/f51ab2df7683fdcfdf023685cfb7793336b7ed79/slot/src/constant.rs#L1-L3 and https://github.com/cartridge-gg/slot/blob/d87a0bc918711b7c4da7c56b71535dc38cbf1bdb/cli/src/command/auth/login.rs#L37

**Comment by kariy** [comment]
completed #68
